stages:
    - build-with-altunity
   

build-windows-with-altunity:
    rules:
        - if: '$CI_COMMIT_MESSAGE != $TEST_COMMIT_MESSAGE && $CI_COMMIT_REF_NAME == "master"'
          when: never
        - when: always
    stage: build-with-altunity
    tags:
      - unity
      - windows
    script:
    - git submodule update --init --force
    - $UNITY_2019_2_HOME -batchmode -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod BuildTrashCat.WindowsBuildInspectorWithAltUnity -logFile buildWindows.log -quit
    - ls
    artifacts:
      when: always
      expire_in: 60 days
      paths:
        - TrashCat/TrashCatWindowsTest
        - buildWindows.log
