stages:
  - build-with-altunity

build-windows-with-altunity:
  stage: build-with-altunity
  tags:
    - unity
    - mac
  script:
    - git submodule update --init --force
    - cd TrashCat/Assets/altunitytester
    - git checkout master
    - git pull
    - git log -1
    - cd ../../..
    - $UNITY_2019_2_HOME -batchmode -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod BuildTrashCat.WindowsBuildInspectorWithAltUnity -logFile buildWindows.log -quit
    - ls
  artifacts:
    when: always
    expire_in: 60 days
    paths:
      - TrashCat/TrashCatWindowsTest
      - buildWindows.log

build-mac-with-altunity:
  stage: build-with-altunity
  tags:
    - unity
    - mac
  script:
    - git submodule update --init --force
    - cd TrashCat/Assets/altunitytester
    - git checkout master
    - git pull
    - git log -1
    - cd ../../..
    - $UNITY_2019_2_HOME -batchmode -buildTarget StandaloneOSX -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod AssetBundles.AssetBundlesMenuItems.BuildAssetBundles -logFile buildAssetBundles.log -quit
    - cp -rf TrashCat/AssetBundles/Android TrashCat/Assets/StreamingAssets/AssetBundles/StandaloneOSX
    - $UNITY_2019_2_HOME -batchmode -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod BuildTrashCat.MacOSBuildInspectorWithAltUnity -logFile buildMac.log -quit
    - ls
  artifacts:
    when: always
    expire_in: 60 days
    paths:
      - TrashCat/TrashCatTest.app
      - buildMac.log

build-android-with-altunity:
  stage: build-with-altunity
  tags:
    - unity
    - mac
  script:
    - git submodule update --init --force
    - cd TrashCat/Assets/altunitytester
    - git checkout master
    - git pull
    - git log -1
    - cd ../../..
    - $UNITY_2019_2_HOME -batchmode -buildTarget Android -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod AssetBundles.AssetBundlesMenuItems.BuildAssetBundles -logFile buildAssetBundles.log -quit
    - cp -rf TrashCat/AssetBundles/Android TrashCat/Assets/StreamingAssets/AssetBundles/Android
    - PROXY_HOST=$PROXY_HOST $UNITY_2019_2_HOME -batchmode -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod BuildTrashCat.AndroidBuild -logFile buildAndroid.log -quit
    - ls
  artifacts:
    when: always
    expire_in: 60 days
    paths:
      - TrashCat/TraschatAndroidTest
      - buildAssetBundles.log
      - buildAndroid.log
