stages:
    - build-with-altunity
   

build-windows-with-altunity:
    stage: build-with-altunity
    tags:
      - unity
      - mac
    script:
    - git submodule update --init --force
    - $UNITY_2019_2_HOME -batchmode -projectPath ${CI_PROJECT_DIR}/TrashCat -executeMethod BuildTrashCat.WindowsBuildInspectorWithAltUnity -logFile buildWindows.log -quit
    - ls
    artifacts:
      when: always
      expire_in: 60 days
      paths:
        - TrashCat/TrashCatWindowsTest
        - buildWindows.log
