name: Build TrashCat
on:
  workflow_dispatch: {}
jobs:
  build-windows:
    runs-on: [macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Init submodule
        run: git submodule update --init --force
        
      - name: Go to Trashcat
        run: cd TrashCat

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          buildMethod: BuildTrashCat.WindowsBuildInspectorWithAltUnity
          targetPlatform: StandaloneWindows
      - uses: actions/upload-artifact@v2
        with:
          path: TrashCatWindowsTest
