name: Build TrashCat

on: [push]

jobs:
  build-for-all-supported-platforms:
    name: Build Trashcat for ${{ matrix.name }}
    runs-on: [ubuntu-latest]

    strategy:
      fail-fast: false

    # matrix:
    #   name:
    #     - macOSWithAltTester
    #     - WindowsWithAltTester
    #     - iOSWithAltTester
    #     - AndroidWithAltTester
    #     - macOSWithAltTesterIL2CPP
    #     - WindowsWithAltTesterIL2CPP
    #   include:
    #     - name: macOSWithAltTester
    #       targetPlatform: StandaloneOSX
    #       buildMethod: BuildTrashCat.macOSBuildWithAltTester
    #     - name: WindowsWithAltTester
    #       targetPlatform: StandaloneWindows
    #       buildMethod: BuildTrashCat.WindowsBuildWithAltTester
    #     - name: iOSWithAltTester
    #       targetPlatform: iOS
    #       buildMethod: BuildTrashCat.iOSBuildWithAltTester
    #     - name: AndroidWithAltTester
    #       targetPlatform: Android
    #       buildMethod: BuildTrashCat.AndroidBuildWithAltTester
    #     - name: macOSWithAltTesterIL2CPP
    #       targetPlatform: StandaloneOSX
    #       buildMethod: BuildTrashCat.macOSBuildWithAltTesterIL2CPP
    #     - name: WindowsWithAltTesterIL2CPP
    #       targetPlatform: StandaloneWindows
    #       buildMethod: BuildTrashCat.WindowsBuildWithAltTesterIL2CPP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add AltTester Unity SDK
        run: git submodule update --init --force

      - uses: actions/cache@v2
        with:
          path: TrashCat/Library
          key: Library-StandaloneWindows64
          restore-keys: Library-StandaloneWindows64

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: TrashCat/
          # targetPlatform: Android
          # buildMethod: BuildTrashCat.AndroidBuild
          targetPlatform: StandaloneWindows
          buildMethod: BuildTrashCat.WindowsBuildWithAltTester

      - uses: actions/upload-artifact@v2
        with:
          name: Builds
          path: TrashCat/Builds
